trying to exit

diff --git a/.github/workflows/gce_ssh_update_code.yaml b/.github/workflows/gce_ssh_update_code.yaml
--- a/.github/workflows/gce_ssh_update_code.yaml
+++ b/.github/workflows/gce_ssh_update_code.yaml
@@ -140,7 +140,8 @@ jobs:
           sed -i 's/daemon=False/daemon=True/g' app/app.py &&
           sudo ./venv/bin/python app/app.py &&
           sed -i 's/daemon=False/daemon=True/g' app/app.py &&
-          pgrep -u root python >/dev/null && echo "Success" exit 1 || echo "[ERROR] Error! No running worker process" exit 1
+          pgrep -u root python >/dev/null && echo "Success" exit 1 || echo "[ERROR] Error! No running worker process" exit 1 &&
+          echo "[ERROR] Error! No running worker process" exit 3
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
         pwd
@@ -152,7 +153,8 @@ jobs:
         s_command: |-
           ls -al &&
           sudo su &&
-          sudo /opt/fieldman/osa/briar-osa/flask/venv/bin/gunicorn --workers 1 --bind 127.0.0.1:5000 -m 007 wsgi:app &&
+          cd /opt/fieldman/osa/briar-osa/flask &&
+          sudo ./venv/bin/gunicorn --workers 1 --bind 127.0.0.1:5000 -m 007 wsgi:app &&
           ls -al
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
