enhance exit

diff --git a/.github/workflows/gce_ssh_update_code.yaml b/.github/workflows/gce_ssh_update_code.yaml
--- a/.github/workflows/gce_ssh_update_code.yaml
+++ b/.github/workflows/gce_ssh_update_code.yaml
@@ -108,8 +108,6 @@ jobs:
           ls -al
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
-        pwd
-        ls -al
 
     # SSH to machinge
     - name: Update flask dependency requirements
@@ -127,11 +125,9 @@ jobs:
           ls -al
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
-        pwd
-        ls -al
 
     # SSH to machinge
-    - name: Checking bottle to run
+    - name: Run bottle
       env:
         s_command: |-
           ls -al &&
@@ -139,13 +135,28 @@ jobs:
           cd /opt/fieldman/osa/briar-osa &&
           sed -i 's/daemon=False/daemon=True/g' app/app.py &&
           sudo ./venv/bin/python app/app.py &&
-          sed -i 's/daemon=False/daemon=True/g' app/app.py &&
-          pgrep -u root python >/dev/null && echo "Success" exit 0 || echo "[ERROR] Error! No running worker process" exit 3
-          echo "[ERROR] Error! No running worker process" exit 1
+          sed -i 's/daemon=True/daemon=False/g' app/app.py &&
+          pgrep -u root python >/dev/null && echo "Success" exit 0 || echo "[ERROR] Error! No running worker process" exit 1
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
-        pwd
-        ls -al
+
+    - name: Wait for bottle 5 seconds
+      uses: jakejarvis/wait-action@master
+      with:
+        time: '5s'
+
+    # SSH to machinge
+    - name: Checking bottle to run
+      env:
+        s_command: |-
+          sudo -H -u root bash -c 'kill -9 `pgrep -u root python`' > /dev/null 2>&1 &&
+          pgrep -u root python >/dev/null && echo "Success" exit 0 || echo "[ERROR] Error! No running worker process" exit 3
+      run: |-
+        export result=$(gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command)
+        if contains(result, 'Error'); then
+          echo "Game over!"
+          exit 1
+        fi
 
     # SSH to machinge
     - name: Checking flask to run
@@ -158,8 +169,6 @@ jobs:
           ls -al
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
-        pwd
-        ls -al
 
     - name: Sleep
       uses: jakejarvis/wait-action@master
