try exit 1

diff --git a/.github/workflows/gce_ssh_update_code.yaml b/.github/workflows/gce_ssh_update_code.yaml
--- a/.github/workflows/gce_ssh_update_code.yaml
+++ b/.github/workflows/gce_ssh_update_code.yaml
@@ -140,7 +140,8 @@ jobs:
           sed -i 's/daemon=False/daemon=True/g' app/app.py &&
           sudo ./venv/bin/python app/app.py &&
           sed -i 's/daemon=False/daemon=True/g' app/app.py &&
-          pgrep -u root python >/dev/null && echo "Success" exit 0 || echo "[ERROR] Error! No running worker process" exit 1
+          pgrep -u root python >/dev/null && echo "Success" exit 0 || echo "[ERROR] Error! No running worker process" exit 3
+          echo "[ERROR] Error! No running worker process" exit 1
       run: |-
         gcloud compute ssh --project $PROJECT_ID --zone $GCE_INSTANCE_ZONE $GCE_INSTANCE -- $s_command
         pwd
